CC      ?= cc
CP      ?= cp -f
RM      ?= rm -f
MKDIR   ?= mkdir -p
INSTALL ?= install

PREFIX  ?= /usr/local

#CFLAGS += -Wall -std=c99 -pedantic
CFLAGS += -Wall -std=c11 -pedantic

.PHONY: all
all: test test.png

.PHONY: readme_update
readme_update: test
	# Library Version (From clib package metadata)
	jq -r '.version' clib.json | xargs -I{} sed -i 's|<version>.*</version>|<version>{}</version>|' README.md
	jq -r '.version' clib.json | xargs -I{} sed -i 's|<versionBadge>.*</versionBadge>|<versionBadge>![Version {}](https://img.shields.io/badge/version-{}-blue.svg)</versionBadge>|' README.md
	# Test statistics (generated by ./test into test_stats.txt)
	while IFS='=' read -r key value; do \
		sed -i "s|<stat-$$key>.*</stat-$$key>|<stat-$$key>$$value</stat-$$key>|g" README.md; \
	done < test_stats.txt

.PHONY: format
format:
	# pip install clang-format
	clang-format -i *.c
	clang-format -i *.h

.PHONY: test
test: test.c sensor_smoother.c sensor_smoother.h
	$(CC) $(CFLAGS) $(LDFLAGS) -o test test.c sensor_smoother.c -lm
	./test

test.png: test.gnuplot test.csv
	gnuplot test.gnuplot

#.PHONY:
#%.o: %.c
#	$(CC) $(DEP_FLAG) $(CFLAGS) $(LDFLAGS) -o $@ -c $<

.PHONY: clean
clean:
	$(RM) test test.csv test_stats.txt
